schema_version = "1.0.0"

id = "MustardUI"
version = "2025.8.1"
name = "MustardUI"
tagline = "Easy-to-use UI for human characters"
maintainer = "Mustard"
type = "add-on"

website = "https://github.com/Mustard2/MustardUI/"

tags = ["User Interface"]

blender_version_min = "5.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export templates from/to disk"
